//! Linux workload containment. Workload identities are generated by the host;
//! titles, directory names, and arbitrary foreign PIDs are never unit names.
mod owner;
mod systemd;
mod unit_job;

pub use owner::wait_for_gui_exit;
pub use systemd::{Manager, ScopeLimits, ScopeMembership};

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct WorkloadId {
    instance: String,
    sequence: u64,
}

impl WorkloadId {
    pub fn new(instance: &str, sequence: u64) -> Result<Self, String> {
        if instance.len() != 32
            || !instance
                .bytes()
                .all(|byte| byte.is_ascii_hexdigit() && !byte.is_ascii_uppercase())
            || sequence == 0
        {
            return Err("invalid generated workload identity".into());
        }
        Ok(Self {
            instance: instance.to_owned(),
            sequence,
        })
    }

    #[must_use]
    pub fn scope(&self) -> String {
        format!("tornadotty-{}-pane-{}.scope", self.instance, self.sequence)
    }

    #[must_use]
    pub fn owner(&self) -> String {
        format!("tornadotty-{}-owner.service", self.instance)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn untrusted_names_cannot_become_workload_units() {
        for instance in [
            "",
            "../../app.slice",
            "other.service",
            "a;b",
            "A0000000000000000000000000000000",
        ] {
            assert!(WorkloadId::new(instance, 1).is_err());
        }
        let instance = "a0000000000000000000000000000000";
        assert!(WorkloadId::new(instance, 0).is_err());
        let first = WorkloadId::new(instance, 1).unwrap();
        let next = WorkloadId::new(instance, 2).unwrap();
        assert_ne!(first.scope(), next.scope());
        assert_eq!(first.owner(), next.owner());
    }
}
